# Generated by GitHub Copilot on 2026-03-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('date_attempt', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='brain_quiz_attempts', to='accounts.account', to_field='username')),
            ],
            options={
                'db_table': 'brain_quiz_attempt',
                'ordering': ['-date_attempt'],
                'constraints': [models.UniqueConstraint(fields=('username', 'attempt_number'), name='unique_brain_attempt_per_user')],
            },
        ),
    ]