# Generated by GitHub Copilot on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_brainquizattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkeletalSignSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=64)),
                ('sign_folder', models.CharField(max_length=64)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('image_png', models.BinaryField()),
                ('feature_vector', models.JSONField()),
                ('source', models.CharField(default='capture', max_length=32)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skeletal_sign_sample',
                'ordering': ['-captured_at'],
            },
        ),
    ]
