# Generated by GitHub Copilot on 2026-04-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skeletalsignsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_key', models.CharField(max_length=64)),
                ('current_term_index', models.PositiveIntegerField(default=0)),
                ('current_term', models.CharField(max_length=32)),
                ('total_terms', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_progress_entries', to='accounts.account')),
            ],
            options={
                'db_table': 'syllabus_progress',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'syllabus_key'), name='unique_syllabus_progress_per_user')],
            },
        ),
    ]