# Generated by Django 6.0.3 on 2026-04-15 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_syllabusprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=100)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history_entries', to='accounts.account')),
            ],
            options={
                'db_table': 'search_history',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['account', '-searched_at'], name='search_hist_account_8377bb_idx')],
            },
        ),
    ]
