# Generated by Django 6.0.3 on 2026-04-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
